export const CLUB_ROLES = [
  { id: 'STUDENT', label: 'Student Member', roleType: 'student' },
  { id: 'FACULTY', label: 'Faculty Coordinator', roleType: 'admin' },
  { id: 'CONVENER', label: 'Convener', roleType: 'admin' },
  { id: 'CO_CONVENER', label: 'Co-Convener', roleType: 'admin' },
  { id: 'PRESIDENT', label: 'President', roleType: 'admin' },
  { id: 'VICE_PRESIDENT', label: 'Vice President', roleType: 'admin' },
  { id: 'STUDENT_COORDINATOR', label: 'Student Coordinator', roleType: 'admin' },
  { id: 'TREASURER', label: 'Treasurer', roleType: 'admin' },
  { id: 'EVENT_MANAGEMENT', label: 'Event Management', roleType: 'admin' },
  { id: 'MEDIA_LEAD', label: 'Media Lead', roleType: 'admin' },
  { id: 'SOCIAL_MEDIA_LEAD', label: 'Social Media Lead', roleType: 'admin' },
  { id: 'TECH_TEAM', label: 'Tech Team', roleType: 'admin' },
  { id: 'PR_TEAM', label: 'PR Team', roleType: 'admin' },
  { id: 'CULTURAL', label: 'Cultural', roleType: 'admin' },
  { id: 'SECRETARY', label: 'Secretary', roleType: 'admin' },
  { id: 'ADMIN', label: 'Administrator', roleType: 'admin' },
]

export const READ_ONLY_CLUB_ROLES = ['FACULTY', 'CONVENER', 'CO_CONVENER']

export function isReadOnlyClubRole(role) {
  return READ_ONLY_CLUB_ROLES.includes(role)
}

export function getRoleLabel(roleId) {
  const r = CLUB_ROLES.find(item => item.id === roleId)
  return r ? r.label : roleId
}

export function toPortalUser(user) {
  if (!user) return null
  const isStudentRole = user.role === 'STUDENT'
  const isReadOnly = isReadOnlyClubRole(user.role)
  const name = user.profile?.name || user.name || 'Member'
  const initials = name.split(/\s+/).filter(Boolean).slice(0, 2).map(p => p[0]).join('').toUpperCase() || 'CS'
  return {
    id: user.id,
    role: user.role,
    isPrimaryAdmin: Boolean(user.isPrimaryAdmin),
    isAdminUser: !isStudentRole,
    isReadOnly,
    name,
    initials,
    memberId: user.memberId,
    permissions: user.permissions || [],
    twoFactorEnabled: user.twoFactorEnabled || false,
    profile: user.profile || {},
  }
}

export const BRANCH_OPTIONS = ['CSE', 'ECE', 'EEE', 'CE', 'ME', 'IT', 'BBA', 'MBA', 'IoT']
export const CSE_SPECIALIZATIONS = ['AIML', 'CS', 'DS', 'General', 'IT', 'IOT', 'AIDS']
export const ACADEMIC_YEARS = [
  { value: 1, label: '1st Year (Freshman / UG)' },
  { value: 2, label: '2nd Year (Sophomore / UG)' },
  { value: 3, label: '3rd Year (Junior / UG)' },
  { value: 4, label: '4th Year (Senior / UG)' },
  { value: 5, label: 'Postgraduate (M.Tech / MCA / MS / MBA)' },
  { value: 6, label: 'PhD / Research Scholar' },
]

export const OFFICIAL_COLLEGES_LIST = [
  'ACE Engineering College, Ghatkesar, Hyderabad',
  'Adikavi Nannaya University, Rajahmundry',
  'Aditya College of Engineering & Technology, Surampalem',
  'Aditya Engineering College, Surampalem',
  'Aditya University, Surampalem',
  'AIIMS Bibinagar (All India Institute of Medical Sciences)',
  'AIIMS Mangalagiri',
  'AIIMS New Delhi',
  'Amity University, Hyderabad / National Campuses',
  'Amrita Vishwa Vidyapeetham (Amrita University)',
  'Andhra Loyola Institute of Engineering and Technology, Vijayawada',
  'Andhra University College of Engineering (AUCE), Visakhapatnam',
  'Annamacharya Institute of Technology and Sciences (AITS), Rajampet',
  'Annamacharya Institute of Technology and Sciences (AITS), Tirupati',
  'Annamacharya University, Rajampet',
  'Anurag College of Engineering, Aushapur, Ghatkesar',
  'Anurag Engineering College, Kodad',
  'Anurag University, Venkatapur, Hyderabad',
  'Ashoka Institute of Engineering and Technology, Yadadri',
  'Audisankara College of Engineering & Technology, Gudur',
  "Aurora's Degree & PG College, Chikkadpally, Hyderabad",
  "Aurora's Engineering College, Bhongir",
  "Aurora's Scientific, Technological & Research Academy, Bandlaguda, Hyderabad",
  'AVN Institute of Engineering and Technology (AVNIET), Ibrahimpatnam',
  'B.E.S.T Innovation University, Andhra Pradesh',
  'B.V. Raju Institute of Technology (BVRIT Autonomous), Narsapur, Medak',
  'Bapatla Engineering College, Guntur',
  'Bharat Institute of Engineering and Technology (BIET), Ibrahimpatnam',
  'Bhaskar Engineering College, Yenkapally, Moinabad',
  'BITS Pilani, Goa Campus',
  'BITS Pilani, Hyderabad Campus, Shamirpet',
  'BITS Pilani, Pilani Campus',
  'BMS College of Engineering, Bengaluru',
  "Brilliant Grammar School Educational Society's Group of Institutions, Abdullapurmet",
  'Brilliant Institute of Engineering & Technology, Hayathnagar',
  'BVRIT Hyderabad College of Engineering for Women (Autonomous), Bachupally',
  'Central University of Andhra Pradesh (CUAP), Anantapur',
  'Centurion University of Technology and Management, Vizianagaram',
  'Chaitanya (Deemed to be University), Hanamkonda, Warangal',
  'Chaitanya Bharathi Institute of Technology (CBIT Autonomous), Gandipet, Hyderabad',
  'Christ University, Bengaluru / NCR / Lavasa',
  'CMR College of Engineering & Technology (CMRCET Autonomous), Kandlakoya, Medchal',
  'CMR Engineering College (CMREC Autonomous), Kandlakoya, Medchal',
  'CMR Institute of Technology (CMRIT Autonomous), Kandlakoya, Medchal',
  'CMR Technical Campus (CMRTC Autonomous), Kandlakoya, Medchal',
  'College of Engineering Guindy, Anna University, Chennai',
  'College of Engineering, Pune (COEP Technological University)',
  'CVR College of Engineering (Autonomous), Mangalpalli, Ibrahimpatnam',
  'D.Y. Patil International University, Pune',
  'Damodaram Sanjivayya National Law University (DSNLU), Visakhapatnam',
  'Delhi Technological University (DTU), New Delhi',
  'Dhanekula Institute of Engineering and Technology, Ganguru, Vijayawada',
  'Dr. B.R. Ambedkar Open University, Jubilee Hills, Hyderabad',
  'Dr. B.R. Ambedkar University, Srikakulam',
  'Dr. K.V. Subba Reddy Institute of Technology, Kurnool',
  'Dr. YSR Architecture and Fine Arts University, Kadapa',
  'Dravidian University, Srinivasavanam, Kuppam',
  'Ellanki College of Engineering and Technology, Patancheru',
  'English and Foreign Languages University (EFLU), Tarnaka, Hyderabad',
  'G. Narayanamma Institute of Technology and Science for Women (GNITS Autonomous), Shaikpet',
  'G. Pulla Reddy Engineering College (GPREC Autonomous), Kurnool',
  'G. Pullaiah College of Engineering and Technology, Kurnool',
  'Gayatri Vidya Parishad College of Engineering (GVPCE Autonomous), Visakhapatnam',
  'Geethanjali College of Engineering and Technology (GCET Autonomous), Keesara, Hyderabad',
  'GITAM Deemed to be University, Hyderabad Campus, Rudraram',
  'GITAM Deemed to be University, Visakhapatnam Campus',
  'Global Institute of Engineering and Technology, Chilkur, Moinabad',
  'GMR Institute of Technology (GMRIT Autonomous), Rajam',
  'Gokaraju Rangaraju Institute of Engineering and Technology (GRIET Autonomous), Bachupally',
  'Gudlavalleru Engineering College (Seshadri Rao Gudlavalleru), Krishna District',
  'Guru Nanak Institute of Technology (GNIT Autonomous), Ibrahimpatnam',
  'Guru Nanak Institutions Technical Campus (GNITC Autonomous), Ibrahimpatnam',
  'Gurunanak University, Ibrahimpatnam, Hyderabad',
  'Hindustan Institute of Technology and Science (HITS), Padur, Chennai',
  'Holy Mary Institute of Technology & Science (Autonomous), Bogaram, Keesara',
  'Hyderabad Institute of Technology and Management (HITAM Autonomous), Medchal',
  'ICFAI Foundation for Higher Education (IFHE / IBS / FST), Shankarpally, Hyderabad',
  'IIIT Allahabad (Indian Institute of Information Technology)',
  'IIIT Bangalore (International Institute of Information Technology)',
  'IIIT Delhi (Indraprastha Institute of Information Technology)',
  'IIIT Gwalior (ABV-IIITM)',
  'IIIT Hyderabad (International Institute of Information Technology), Gachibowli',
  'IIIT Jabalpur (PDPM IIITDM)',
  'IIIT Kancheepuram (IIITDM)',
  'IIIT Kottayam, Kerala',
  'IIIT Kurnool (Indian Institute of Information Technology Design & Manufacturing)',
  'IIIT Lucknow, Uttar Pradesh',
  'IIIT Nagpur, Maharashtra',
  'IIIT Pune, Maharashtra',
  'IIIT Sri City, Chittoor, Andhra Pradesh',
  'IIIT Vadodara, Gujarat',
  'IIM Ahmedabad',
  'IIM Bangalore',
  'IIM Calcutta',
  'IIM Visakhapatnam',
  'IISc Bangalore (Indian Institute of Science)',
  'IIT Bhubaneswar (Indian Institute of Technology)',
  'IIT Bombay (Indian Institute of Technology Bombay, Powai)',
  'IIT Delhi (Indian Institute of Technology Delhi, Hauz Khas)',
  'IIT Gandhinagar (Indian Institute of Technology)',
  'IIT Guwahati (Indian Institute of Technology)',
  'IIT Hyderabad (Indian Institute of Technology Hyderabad, Kandi, Sangareddy)',
  'IIT Indore (Indian Institute of Technology)',
  'IIT Jodhpur (Indian Institute of Technology)',
  'IIT Kanpur (Indian Institute of Technology Kanpur)',
  'IIT Kharagpur (Indian Institute of Technology)',
  'IIT Madras (Indian Institute of Technology Madras, Chennai)',
  'IIT Mandi (Indian Institute of Technology)',
  'IIT Palakkad (Indian Institute of Technology)',
  'IIT Patna (Indian Institute of Technology)',
  'IIT Roorkee (Indian Institute of Technology Roorkee)',
  'IIT Ropar (Indian Institute of Technology)',
  'IIT Tirupati (Indian Institute of Technology Tirupati, Yerpedu)',
  'IIT Varanasi (BHU - Indian Institute of Technology)',
  'Indian Statistical Institute (ISI), Kolkata / Delhi / Bengaluru / Hyderabad',
  'Indur Institute of Engineering and Technology, Ponnal, Siddipet',
  'Institute of Aeronautical Engineering (IARE Autonomous), Dundigal, Hyderabad',
  'ISL Engineering College, Bandlaguda, Chandrayangutta, Hyderabad',
  'J.B. Institute of Engineering and Technology (JBIET Autonomous), Moinabad, Hyderabad',
  'Jadavpur University, Kolkata',
  'Jamia Millia Islamia, New Delhi',
  'Jawaharlal Nehru Architecture and Fine Arts University (JNAFAU), Masab Tank, Hyderabad',
  'Jawaharlal Nehru Technological University Anantapur (JNTUA)',
  'Jawaharlal Nehru Technological University Gurajada Vizianagaram (JNTUGV)',
  'Jawaharlal Nehru Technological University Kakinada (JNTUK)',
  'JNTU College of Engineering, Anantapur (JNTUACEA Autonomous)',
  'JNTU College of Engineering, Hyderabad (JNTUH UCEH Autonomous), Kukatpally',
  'JNTU College of Engineering, Jagtial (JNTUH UCEJ), Nachupally',
  'JNTU College of Engineering, Kakinada (JNTUCEK Autonomous)',
  'JNTU College of Engineering, Manthani (JNTUH UCEM), Centenary Colony',
  'JNTU College of Engineering, Narasaraopet (JNTUK UCEN)',
  'JNTU College of Engineering, Rajanna Sircilla (JNTUH UCES)',
  'JNTU College of Engineering, Sultanpur (JNTUH UCESP), Sangareddy',
  'JNTU College of Engineering, Vizianagaram (JNTUCEV Autonomous)',
  'JNTU College of Engineering, Wanaparthy (JNTUH UCEW)',
  'Joginpally B.R. Engineering College (JBREC), Yenkapally, Moinabad',
  'Jyothishmathi Institute of Technology and Science, Nustulapur, Karimnagar',
  'K L Deemed to be University, Bowrampet / Aziznagar, Hyderabad Campus',
  'K L Deemed to be University, Vaddeswaram, Guntur / Vijayawada Campus',
  'Kakatiya Institute of Technology and Science (KITS Autonomous), Yerragattu, Warangal',
  'Kakatiya University College of Engineering and Technology (KUCE&T), Warangal',
  'Kalasalingam Academy of Research and Education, Krishnankoil, Tamil Nadu',
  'Kaloji Narayana Rao University of Health Sciences (KNRUHS), Warangal',
  'Kamala Institute of Technology and Science (KITS), Singapuram, Huzurabad',
  'Kasireddy Narayanreddy College of Engineering & Research, Abdullapurmet',
  'Kaveri University, Hyderabad',
  'Keshav Memorial Engineering College (KMEC), Kandlakoya',
  'Keshav Memorial Institute of Technology (KMIT Autonomous), Narayanguda, Hyderabad',
  'KG Reddy College of Engineering and Technology (KGRCET Autonomous), Moinabad',
  'KKR & KSR Institute of Technology and Sciences (KITS Autonomous), Vinjanampadu, Guntur',
  'Kshatriya College of Engineering (KCEA), Armoor, Nizamabad',
  'Lakireddy Bali Reddy College of Engineering (LBRCE Autonomous), Mylavaram, Krishna District',
  'Lords Institute of Engineering and Technology (LIET Autonomous), Himayat Sagar, Hyderabad',
  'Loyola Academy Degree and PG College (Autonomous), Old Alwal, Secunderabad',
  'Madanapalle Institute of Technology and Science (MITS Autonomous), Madanapalle',
  'Madira Institute of Technology and Science, Kodad',
  'Mahatma Gandhi Institute of Technology (MGIT Autonomous), Gandipet, Hyderabad',
  'Mahatma Gandhi University, Anneparthy, Nalgonda',
  'Mahindra University, Bahadurpally, Jeedimetla, Hyderabad',
  'Malla Reddy College of Engineering & Technology (MRCET Autonomous), Maisammaguda, Secunderabad',
  'Malla Reddy College of Engineering (MRCE), Maisammaguda, Secunderabad',
  'Malla Reddy College of Engineering for Women (MRCW), Maisammaguda, Secunderabad',
  'Malla Reddy (MR) Deemed to be University, Maisammaguda, Hyderabad',
  'Malla Reddy Engineering College (MREC Autonomous), Maisammaguda, Secunderabad',
  'Malla Reddy Engineering College for Women (MRECW Autonomous), Maisammaguda, Secunderabad',
  'Malla Reddy Institute of Engineering & Technology (MRIET), Maisammaguda, Secunderabad',
  'Malla Reddy Institute of Medical Sciences (MRIMS), Suraram, Hyderabad',
  'Malla Reddy Institute of Pharmaceutical Sciences, Maisammaguda',
  'Malla Reddy Institute of Technology & Science (MRITS), Maisammaguda, Secunderabad',
  'Malla Reddy Pharmacy College, Maisammaguda',
  'Malla Reddy University (MRU Private University), Maisammaguda, Hyderabad',
  "Malla Reddy Women's College, Maisammaguda",
  'Manipal Academy of Higher Education (MAHE - Manipal University), Manipal / Bengaluru',
  'Manipal University, Jaipur',
  'Matrusri Engineering College (MECS Autonomous), Saidabad, Hyderabad',
  'Maulana Azad National Institute of Technology (MANIT), Bhopal',
  'Maulana Azad National Urdu University (MANUU), Gachibowli, Hyderabad',
  'Methodist College of Engineering and Technology (MCET Autonomous), Abids, Hyderabad',
  'MLR Institute of Technology (MLRIT Autonomous), Dundigal, Hyderabad',
  'MNR University / Medical College, Sangareddy',
  'Muffakham Jah College of Engineering and Technology (MJCET), Banjara Hills, Hyderabad',
  'MVGR College of Engineering (Autonomous), Chintalavalasa, Vizianagaram',
  'MVSR Engineering College (Maturi Venkata Subba Rao Autonomous), Nadergul, Hyderabad',
  'NALSAR University of Law, Justice City, Shamirpet, Hyderabad',
  'Nalla Malla Reddy Engineering College (NMREC Autonomous), Divyanagar, Ghatkesar',
  "Nalla Narasimha Reddy Education Society's Group of Institutions (NNRG Autonomous), Chowdariguda, Ghatkesar",
  'Narasaraopeta Engineering College (NEC Autonomous), Narasaraopet',
  'National Institute of Design (NID), Ahmedabad / Andhra Pradesh',
  'National Institute of Fashion Technology (NIFT), Madhapur, Hyderabad',
  'National Institute of Technology Calicut (NITC)',
  'National Institute of Technology Karnataka (NITK Surathkal)',
  'National Institute of Technology Rourkela (NIT Rourkela)',
  'National Institute of Technology Tiruchirappalli (NIT Trichy)',
  'National Institute of Technology Warangal (NIT Warangal / NITW)',
  'National Institute of Technology, Andhra Pradesh (NIT Tadepalligudem)',
  'Nawab Shah Alam Khan College of Engineering and Technology, New Malakpet, Hyderabad',
  'Neil Gogte Institute of Technology (NGIT), Peerzadiguda, Uppal, Hyderabad',
  'Netaji Subhas University of Technology (NSUT), New Delhi',
  'NICMAR University, Shamirpet, Hyderabad',
  'NMIMS Deemed to be University, Jadcherla / Tarnaka, Hyderabad Campus',
  'Osmania University College of Engineering (OUCE Autonomous), University Campus, Hyderabad',
  'Osmania University College of Technology (OUCT Autonomous), University Campus, Hyderabad',
  'Osmania University (Main Campus), Tarnaka, Hyderabad',
  'Palamuru University, Bandameedipally, Mahabubnagar',
  'PES University, Ring Road / Electronic City, Bengaluru',
  'Pragati Engineering College (Autonomous), Surampalem, Kakinada',
  'Prasad V. Potluri Siddhartha Institute of Technology (PVPSIT Autonomous), Kanuru, Vijayawada',
  'Princeton Institute of Engineering and Technology for Women, Chowdaryguda, Ghatkesar',
  'Professor Jayashankar Telangana State Agricultural University (PJTSAU), Rajendranagar, Hyderabad',
  'PSG College of Technology, Peelamedu, Coimbatore',
  'R.V. College of Engineering (RVCE), Bengaluru',
  'Rajiv Gandhi University of Knowledge Technologies (RGUKT - IIIT Basar), Nirmal, Telangana',
  'Rajiv Gandhi University of Knowledge Technologies (RGUKT - IIIT Nuzvid), Andhra Pradesh',
  'Rajiv Gandhi University of Knowledge Technologies (RGUKT - IIIT RK Valley / Idupulapaya), Kadapa',
  'Rajiv Gandhi University of Knowledge Technologies (RGUKT - IIIT Srikakulam), Andhra Pradesh',
  'Rajiv Gandhi University of Knowledge Technologies (RGUKT - IIIT Ongole), Andhra Pradesh',
  'Rashtriya Sanskrit Vidyapeetha (National Sanskrit University), Tirupati',
  'RGM College of Engineering and Technology (RGMCET Autonomous), Nandyal',
  'S.R. International Institute of Technology (SRIIT), Rampally, Keesara',
  'Sai Spurthi Institute of Technology, B. Gangaram, Sathupally, Khammam',
  'Sammakka Sarakka Central Tribal University, Mulugu, Telangana',
  'Samskruti College of Engineering and Technology, Kondapur, Ghatkesar',
  'Santhiram Engineering College, Nandyal',
  'Sardar Vallabhbhai National Institute of Technology (SVNIT), Surat',
  'Satavahana University, Malkapur Road, Karimnagar',
  'Scient Institute of Technology, Ibrahimpatnam',
  'Seshadri Rao Gudlavalleru Engineering College (SRGEC Autonomous), Gudlavalleru',
  'Shadan College of Engineering and Technology, Peerancheru, Himayat Sagar Road, Hyderabad',
  "Shadan Women's College of Engineering and Technology, Khairatabad, Hyderabad",
  'Shiv Nadar University, Greater Noida, Delhi-NCR / Chennai',
  'Shri Ramdeobaba College of Engineering and Management (RCOEM), Nagpur',
  'Siddhartha Academy of Higher Education, Vijayawada',
  'Siddhartha Institute of Engineering and Technology, Vinobha Nagar, Ibrahimpatnam',
  'Siddhartha Institute of Technology and Sciences, Narapally, Korremula, Ghatkesar',
  'Sphoorthy Engineering College (Autonomous), Nadergul, Sagar Road, Hyderabad',
  'SR University (SRU Private University), Ananthasagar, Hasanparthy, Warangal',
  'Sree Chaitanya College of Engineering, LMD Colony, Karimnagar',
  'Sree Dattha Group of Educational Institutions, Sheriguda, Ibrahimpatnam',
  'Sree Dattha Institute of Engineering and Science, Sheriguda, Ibrahimpatnam',
  'Sree Rama Engineering College, Rami Reddy Nagar, Tirupati',
  'Sree Vahini Institute of Science and Technology, Tiruvuru, Krishna District',
  'Sree Venkateswara College of Engineering, Golden Nagar, Kodavalur, Nellore',
  'Sree Vidyanikethan Engineering College (Mohan Babu University), Sree Sainath Nagar, Tirupati',
  'Sreenidhi Institute of Science and Technology (SNIST Autonomous), Yamnampet, Ghatkesar',
  'Sreenidhi University, Ghatkesar, Hyderabad',
  'Sreyas Institute of Engineering and Technology (Autonomous), Bandlaguda, Nagole, Hyderabad',
  'Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya (SCSVMV University), Kanchipuram',
  'Sri Indu College of Engineering and Technology (Autonomous), Sheriguda, Ibrahimpatnam',
  'Sri Indu Institute of Engineering and Technology, Sheriguda, Ibrahimpatnam',
  'Sri Konda Laxman Telangana State Horticultural University, Mulugu, Siddipet',
  "Sri Padmavati Mahila Visvavidyalayam (Women's University), Padmavathi Nagar, Tirupati",
  'Sri Sai Jyothi Engineering College, Vattinagulapally, Gandipet',
  'Sri Sairam Engineering College, West Tambaram, Chennai',
  'Sri Sathya Sai Institute of Higher Learning, Prasanthi Nilayam, Puttaparthi',
  'Sri Sivani College of Engineering, Chilakapalem, Srikakulam',
  'Sri Vasavi Engineering College (Autonomous), Pedatadepalli, Tadepalligudem',
  'Sri Venkateswara College of Engineering and Technology (SVCET Autonomous), R.V.S. Nagar, Chittoor',
  'Sri Venkateswara College of Engineering, Karakambadi Road, Tirupati',
  'Sri Venkateswara University College of Engineering (SVUCE Autonomous), Tirupati',
  'Sri Venkateswara University (SVU), Tirupati',
  'Sri Venkateswara Veterinary University, Tirupati',
  'SRM Institute of Science and Technology (SRM University - Kattankulathur / Ramapuram), Chennai',
  'SRM University AP, Neerukonda, Mangalagiri, Amaravati, Andhra Pradesh',
  'SSN College of Engineering, Kalavakkam, Chennai',
  "St. Ann's College of Engineering & Technology, Nayunipalli, Chirala",
  "St. Joseph's Degree & PG College, King Koti, Hyderabad",
  "St. Martin's Engineering College (SMEC Autonomous), Dhulapally, Secunderabad",
  "St. Mary's Engineering College, Deshmukhi, Pochampally",
  "St. Mary's Group of Institutions, Chebrolu, Guntur / Deshmukhi, Hyderabad",
  "St. Peter's Engineering College (Autonomous), Maisammaguda, Medchal",
  'Stanley College of Engineering and Technology for Women (Autonomous), Chapel Road, Abids, Hyderabad',
  'Sumathi Reddy Institute of Technology for Women, Ananthasagar, Hasanparthy, Warangal',
  'Suravaram Prathapa Reddy Telugu University, Public Gardens, Hyderabad',
  'Symbiosis International University (SIU), Mamidipally, Hyderabad / Pune',
  'Talla Padmavathi College of Engineering, Somidi, Kazipet, Warangal',
  'Teegala Krishna Reddy Engineering College (TKREC), Medbowli, Meerpet, Hyderabad',
  'Telangana University, Dichpally, Nizamabad',
  'Thapar Institute of Engineering and Technology (TIET), Patiala, Punjab',
  'TKR College of Engineering and Technology (TKRCET Autonomous), Medbowli, Meerpet, Hyderabad',
  'Trinity College of Engineering and Technology, Bandarikunta, Peddapalli / Karimnagar',
  'University College of Engineering, Kakatiya University, Kothagudem',
  'University College of Engineering, Osmania University (UCEOU Autonomous), Hyderabad',
  'University College of Technology, Osmania University (OUCT Autonomous), Hyderabad',
  'University of Delhi (DU), New Delhi',
  'University of Hyderabad (UoH / HCU Central University), Gachibowli, Hyderabad',
  'Usha Rama College of Engineering and Technology, Telaprolu, Unguturu, Krishna District',
  'Vaagdevi College of Engineering (Autonomous), Bollikunta, Warangal',
  'Vaagdevi Engineering College, Bollikunta, Warangal',
  'Vageshwari College of Engineering, Ramakrishna Colony, Karimnagar',
  'Vardhaman College of Engineering (Autonomous), Kacharam, Shamshabad, Hyderabad',
  'Vasavi College of Engineering (VCE Autonomous), Ibrahimbagh, Hyderabad',
  'Veera Naari Chakali Ilamma Women\'s University (TMV), Koti, Hyderabad',
  'Vel Tech Rangarajan Dr. Sagunthala R&D Institute of Science and Technology, Avadi, Chennai',
  'Vellore Institute of Technology (VIT Bhopal University), Kothri Kalan, Madhya Pradesh',
  'Vellore Institute of Technology (VIT University), Katpadi, Vellore / Chennai',
  'Vellore Institute of Technology (VIT-AP University), Inavolu, Beside AP Secretariat, Amaravati',
  'Vidya Jyothi Institute of Technology (VJIT Autonomous), Aziznagar Gate, C.B. Post, Hyderabad',
  'Vignan Institute of Technology and Science (VITS Autonomous), Deshmukhi, Pochampally',
  "Vignan's Foundation for Science, Technology and Research (Vignan University), Vadlamudi, Guntur",
  "Vignan's Institute of Information Technology (VIIT Autonomous), Duvvada, Visakhapatnam",
  "Vignan's Institute of Management and Technology for Women (VMTW), Kondapur, Ghatkesar",
  'Vignana Bharathi Institute of Technology (VBIT Autonomous), Aushapur, Ghatkesar',
  'Vijaya Krishna Institute of Technology & Sciences, Palamakula, Shamshabad',
  'Vikas College of Engineering and Technology, Nunna, Vijayawada',
  'Vikrama Simhapuri University, Kakutur, Nellore',
  'Vishwa Vishwani Institute of Systems and Management, Boston House, Thumkunta',
  'Vishnu Institute of Technology (VITB Autonomous), Vishnupur, Kovvada, Bhimavaram',
  'Visvesvaraya National Institute of Technology (VNIT), South Ambazari Road, Nagpur',
  'Vivekanandha College of Engineering for Women (Autonomous), Elayampalayam, Tiruchengode',
  'VNR Vignana Jyothi Institute of Engineering and Technology (VNR VJIET Autonomous), Bachupally, Hyderabad',
  'VR Siddhartha Engineering College (VRSEC Autonomous), Kanuru, Vijayawada',
  'Woxsen University, Kamkole, Sadasivpet, Sangareddy, Telangana',
  'Yogi Vemana University (YVU), Vemanapuram, Kadapa',
  'Young India Skill University (YISU), Hyderabad',
  'Other / External University (Specify Below)',
]
