-- Club Management Upgrade Migration

-- 1. Users Table Updates
ALTER TABLE `users` 
  ADD COLUMN IF NOT EXISTS `is_primary_admin` TINYINT(1) NOT NULL DEFAULT 0,
  MODIFY COLUMN `role` ENUM('PRESIDENT', 'VICE_PRESIDENT', 'TREASURER', 'EVENT_MANAGEMENT', 'MEDIA_LEAD', 'TECH_TEAM', 'PR_TEAM', 'CULTURAL', 'SECRETARY', 'ADMIN', 'STUDENT') NOT NULL;

ALTER TABLE `permission_assignments` 
  MODIFY COLUMN `permission` ENUM('ACCOUNT_MANAGEMENT', 'DASHBOARD_VIEW', 'EVENTS_VIEW', 'EVENT_REGISTER', 'REGISTRATIONS_VIEW', 'QR_PASSES_VIEW', 'GALLERY_VIEW', 'CHAT_USE', 'SUGGESTIONS_CREATE', 'FEEDBACK_CREATE', 'NOTIFICATIONS_VIEW', 'PROFILE_EDIT', 'EVENT_MANAGE', 'PAYMENTS_VIEW', 'PAYMENTS_VERIFY', 'GALLERY_MANAGE', 'TEAM_MANAGE', 'SETTINGS_MANAGE', 'AUDIT_VIEW') NOT NULL;

-- Ensure current President is marked as Primary Admin
UPDATE `users` SET `is_primary_admin` = 1 WHERE `role` = 'PRESIDENT' AND `is_primary_admin` = 0;

-- 2. Events Table Updates
ALTER TABLE `events`
  ADD COLUMN IF NOT EXISTS `short_description` VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS `start_time` VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS `end_time` VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS `venue` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `coordinator_name` VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS `coordinator_contact` VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS `organizing_team` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `speaker_name` VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS `speaker_photo` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `speaker_designation` VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS `registration_deadline` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `contact_email` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `contact_phone` VARCHAR(32) NULL,
  ADD COLUMN IF NOT EXISTS `social_links` JSON NULL,
  ADD COLUMN IF NOT EXISTS `rules` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `eligibility` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `required_materials` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `agenda` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `faq` JSON NULL,
  ADD COLUMN IF NOT EXISTS `notes` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `payment_upi_id` VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS `payment_instructions` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `payment_deadline` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `require_payment_proof` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `allow_multiple_activities` TINYINT(1) NOT NULL DEFAULT 0;

-- 3. Event Activities Table
CREATE TABLE IF NOT EXISTS `event_activities` (
  `id` VARCHAR(191) NOT NULL,
  `event_id` VARCHAR(191) NOT NULL,
  `name` VARCHAR(120) NOT NULL,
  `description` VARCHAR(500) NULL,
  `price` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  `capacity` INT NULL,
  `is_available` TINYINT(1) NOT NULL DEFAULT 1,
  `instructions` LONGTEXT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `event_activities_event_id_idx` (`event_id`),
  CONSTRAINT `event_activities_event_id_fkey` FOREIGN KEY (`event_id`) REFERENCES `events` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 4. Event Registrations Table Updates
ALTER TABLE `event_registrations`
  ADD COLUMN IF NOT EXISTS `selected_activities` JSON NULL,
  ADD COLUMN IF NOT EXISTS `total_amount` DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS `payment_status` VARCHAR(50) NOT NULL DEFAULT 'FREE',
  ADD COLUMN IF NOT EXISTS `payment_reference` VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS `payment_proof_url` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `payment_verified_at` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `payment_verified_by` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `payment_notes` VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS `branch` VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS `section` VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS `year` INT NULL,
  ADD COLUMN IF NOT EXISTS `emergency_contact` VARCHAR(32) NULL,
  ADD COLUMN IF NOT EXISTS `team_name` VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS `github` VARCHAR(120) NULL;

-- 5. Club Team Members Table Updates
ALTER TABLE `club_team_members`
  ADD COLUMN IF NOT EXISTS `bio` VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS `college_email` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `contact_email` VARCHAR(191) NULL,
  ADD COLUMN IF NOT EXISTS `instagram_url` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `github_url` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `linkedin_url` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `twitter_url` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `portfolio_url` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `skills` VARCHAR(500) NULL,
  ADD COLUMN IF NOT EXISTS `year` INT NULL,
  ADD COLUMN IF NOT EXISTS `branch` VARCHAR(120) NULL,
  ADD COLUMN IF NOT EXISTS `achievements` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS `approval_status` VARCHAR(50) NOT NULL DEFAULT 'APPROVED';

-- 6. Club Settings Table
CREATE TABLE IF NOT EXISTS `club_settings` (
  `key` VARCHAR(100) NOT NULL,
  `value` LONGTEXT NULL,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`key`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
