ALTER TABLE `users`
  MODIFY `role` ENUM('STUDENT', 'ADMIN', 'PRESIDENT') NOT NULL;

ALTER TABLE `permission_assignments`
  MODIFY `permission` ENUM(
    'ACCOUNT_MANAGEMENT',
    'DASHBOARD_VIEW',
    'EVENTS_VIEW',
    'EVENT_REGISTER',
    'REGISTRATIONS_VIEW',
    'QR_PASSES_VIEW',
    'GALLERY_VIEW',
    'CHAT_USE',
    'SUGGESTIONS_CREATE',
    'FEEDBACK_CREATE',
    'NOTIFICATIONS_VIEW',
    'PROFILE_EDIT'
  ) NOT NULL;
