export const memberPermissions = [
  'ACCOUNT_MANAGEMENT',
  'DASHBOARD_VIEW',
  'EVENTS_VIEW',
  'EVENT_MANAGE',
  'EVENT_REGISTER',
  'REGISTRATIONS_VIEW',
  'PAYMENTS_VIEW',
  'PAYMENTS_VERIFY',
  'QR_PASSES_VIEW',
  'GALLERY_VIEW',
  'GALLERY_MANAGE',
  'REELS_MANAGE',
  'TEAM_MANAGE',
  'SETTINGS_MANAGE',
  'AUDIT_VIEW',
  'CHAT_USE',
  'SUGGESTIONS_CREATE',
  'FEEDBACK_CREATE',
  'NOTIFICATIONS_VIEW',
  'PROFILE_EDIT',
]

export const permissionLabels = {
  ACCOUNT_MANAGEMENT: 'Manage accounts',
  DASHBOARD_VIEW: 'Dashboard access',
  EVENTS_VIEW: 'Browse events',
  EVENT_MANAGE: 'Create and edit events',
  EVENT_REGISTER: 'Register for events',
  REGISTRATIONS_VIEW: 'View registrations',
  PAYMENTS_VIEW: 'View payments',
  PAYMENTS_VERIFY: 'Verify payments',
  QR_PASSES_VIEW: 'View QR passes',
  GALLERY_VIEW: 'Browse photo gallery',
  GALLERY_MANAGE: 'Manage photo gallery',
  REELS_MANAGE: 'Manage campus reels & social streams',
  TEAM_MANAGE: 'Manage club team',
  SETTINGS_MANAGE: 'Manage club settings',
  AUDIT_VIEW: 'View security audit logs',
  CHAT_USE: 'Use club chat',
  SUGGESTIONS_CREATE: 'Submit suggestions',
  FEEDBACK_CREATE: 'Submit feedback',
  NOTIFICATIONS_VIEW: 'View notifications',
  PROFILE_EDIT: 'Edit personal profile',
}

export const clubRoles = [
  { id: 'PRESIDENT', label: 'President', description: 'Full club leadership and primary administration' },
  { id: 'VICE_PRESIDENT', label: 'Vice President', description: 'Broad management and executive operations' },
  { id: 'TREASURER', label: 'Treasurer', description: 'Financial records, payment verification, and revenue exports' },
  { id: 'EVENT_MANAGEMENT', label: 'Event Management', description: 'Event Studio, activities, registrations, and capacity' },
  { id: 'MEDIA_LEAD', label: 'Media Lead', description: 'Gallery albums, event photos, and public showcases' },
  { id: 'SOCIAL_MEDIA_LEAD', label: 'Social Media Lead', description: 'Campus Reels, Instagram sync, social posts, and channel streams' },
  { id: 'TECH_TEAM', label: 'Tech Team', description: 'Technical operations, platform settings, and security' },
  { id: 'PR_TEAM', label: 'PR Team', description: 'Public relations, community outreach, and social links' },
  { id: 'CULTURAL', label: 'Cultural', description: 'Club cultural activities, programs, and social events' },
  { id: 'SECRETARY', label: 'Secretary', description: 'Club records, documentation, and member relations' },
  { id: 'ADMIN', label: 'Administrator', description: 'Platform administration and member management' },
  { id: 'STUDENT', label: 'Student Member', description: 'Official club student member with portal access' },
]

export const rolePermissionMatrix = {
  PRESIDENT: [
    'ACCOUNT_MANAGEMENT',
    'DASHBOARD_VIEW',
    'EVENTS_VIEW',
    'EVENT_MANAGE',
    'EVENT_REGISTER',
    'REGISTRATIONS_VIEW',
    'PAYMENTS_VIEW',
    'PAYMENTS_VERIFY',
    'QR_PASSES_VIEW',
    'GALLERY_VIEW',
    'GALLERY_MANAGE',
    'REELS_MANAGE',
    'TEAM_MANAGE',
    'SETTINGS_MANAGE',
    'AUDIT_VIEW',
    'CHAT_USE',
    'SUGGESTIONS_CREATE',
    'FEEDBACK_CREATE',
    'NOTIFICATIONS_VIEW',
    'PROFILE_EDIT',
  ],
  VICE_PRESIDENT: [
    'ACCOUNT_MANAGEMENT',
    'DASHBOARD_VIEW',
    'EVENTS_VIEW',
    'EVENT_MANAGE',
    'EVENT_REGISTER',
    'REGISTRATIONS_VIEW',
    'PAYMENTS_VIEW',
    'QR_PASSES_VIEW',
    'GALLERY_VIEW',
    'GALLERY_MANAGE',
    'REELS_MANAGE',
    'TEAM_MANAGE',
    'CHAT_USE',
    'NOTIFICATIONS_VIEW',
    'PROFILE_EDIT',
  ],
  TREASURER: [
    'DASHBOARD_VIEW',
    'EVENTS_VIEW',
    'REGISTRATIONS_VIEW',
    'PAYMENTS_VIEW',
    'PAYMENTS_VERIFY',
    'QR_PASSES_VIEW',
    'NOTIFICATIONS_VIEW',
    'PROFILE_EDIT',
  ],
  EVENT_MANAGEMENT: [
    'DASHBOARD_VIEW',
    'EVENTS_VIEW',
    'EVENT_MANAGE',
    'EVENT_REGISTER',
    'REGISTRATIONS_VIEW',
    'QR_PASSES_VIEW',
    'NOTIFICATIONS_VIEW',
    'PROFILE_EDIT',
  ],
  MEDIA_LEAD: [
    'DASHBOARD_VIEW',
    'EVENTS_VIEW',
    'GALLERY_VIEW',
    'GALLERY_MANAGE',
    'REELS_MANAGE',
    'TEAM_MANAGE',
    'NOTIFICATIONS_VIEW',
    'PROFILE_EDIT',
  ],
  SOCIAL_MEDIA_LEAD: [
    'DASHBOARD_VIEW',
    'EVENTS_VIEW',
    'GALLERY_VIEW',
    'GALLERY_MANAGE',
    'REELS_MANAGE',
    'SETTINGS_MANAGE',
    'TEAM_MANAGE',
    'NOTIFICATIONS_VIEW',
    'PROFILE_EDIT',
  ],
  TECH_TEAM: [
    'DASHBOARD_VIEW',
    'EVENTS_VIEW',
    'SETTINGS_MANAGE',
    'NOTIFICATIONS_VIEW',
    'PROFILE_EDIT',
  ],
  PR_TEAM: [
    'DASHBOARD_VIEW',
    'EVENTS_VIEW',
    'REELS_MANAGE',
    'SETTINGS_MANAGE',
    'TEAM_MANAGE',
    'NOTIFICATIONS_VIEW',
    'PROFILE_EDIT',
  ],
  CULTURAL: [
    'DASHBOARD_VIEW',
    'EVENTS_VIEW',
    'EVENT_MANAGE',
    'NOTIFICATIONS_VIEW',
    'PROFILE_EDIT',
  ],
  SECRETARY: [
    'ACCOUNT_MANAGEMENT',
    'DASHBOARD_VIEW',
    'EVENTS_VIEW',
    'REGISTRATIONS_VIEW',
    'TEAM_MANAGE',
    'NOTIFICATIONS_VIEW',
    'PROFILE_EDIT',
  ],
  ADMIN: [
    'ACCOUNT_MANAGEMENT',
    'DASHBOARD_VIEW',
    'EVENTS_VIEW',
    'EVENT_MANAGE',
    'EVENT_REGISTER',
    'REGISTRATIONS_VIEW',
    'PAYMENTS_VIEW',
    'PAYMENTS_VERIFY',
    'GALLERY_VIEW',
    'GALLERY_MANAGE',
    'REELS_MANAGE',
    'TEAM_MANAGE',
    'SETTINGS_MANAGE',
    'AUDIT_VIEW',
    'NOTIFICATIONS_VIEW',
    'PROFILE_EDIT',
  ],
  STUDENT: [
    'DASHBOARD_VIEW',
    'EVENTS_VIEW',
    'EVENT_REGISTER',
    'REGISTRATIONS_VIEW',
    'QR_PASSES_VIEW',
    'GALLERY_VIEW',
    'CHAT_USE',
    'SUGGESTIONS_CREATE',
    'FEEDBACK_CREATE',
    'NOTIFICATIONS_VIEW',
    'PROFILE_EDIT',
  ],
}

export function getRolePermissions(role) {
  return rolePermissionMatrix[role] || rolePermissionMatrix.STUDENT
}
